'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../public/src/engine.js'),C=require('../public/src/content.js'),W=require('../public/data/words.js');
const fresh=()=>E.fresh(17,'2026-09-13'),allowed=new Set(W.allowed.split(' '));
test('exact section and tier book merges preserve identity and stop at six',()=>{for(let tier=1;tier<6;tier++){const s=fresh();s.board[0]={kind:'book',tier,section:'poetry'};s.board[1]={kind:'book',tier,section:'poetry'};assert.equal(E.move(s,0,1).type,'merge');assert.deepEqual(s.board[1],{kind:'book',tier:tier+1,section:'poetry'});assert.equal(s.board[0],null);assert.equal(s.merges,1);assert.equal(s.xp,2);assert.ok(s.catalogued.includes('poetry:'+(tier+1)));}assert.equal(E.compatible({kind:'book',tier:6,section:'fiction'},{kind:'book',tier:6,section:'fiction'}),null);assert.equal(E.compatible({kind:'book',tier:2,section:'fiction'},{kind:'book',tier:2,section:'poetry'}),null);});
test('mismatched tiers and invalid moves do not mutate state',()=>{const s=fresh(),before=E.copy(s);assert.equal(E.move(s,0,10).ok,false);for(const indices of [[0,0],[-1,1],[0,20],[null,1],[0,NaN],[2,3]])assert.equal(E.move(s,...indices).ok,false);assert.deepEqual(s,before);});
test('all twenty-four authentic recipes assemble every named component in either order',()=>{for(const r of C.recipes){for(const reverse of [false,true]){const s=fresh();s.board=Array(20).fill(null);const parts=(reverse?[...r.components].reverse():r.components);parts.forEach((c,i)=>s.board[i]={kind:'ingredient',id:r.id,component:c.id});let target=0;for(let i=1;i<parts.length;i++){const result=E.move(s,i,target);assert.equal(result.type,i===parts.length-1?'dish':'prep');}assert.deepEqual(s.board[target],{kind:'dish',id:r.id});assert.deepEqual(s.discovered,[r.id]);assert.equal(s.dishes,1);}const first=r.components[0].id,second=r.components[1].id;assert.equal(E.compatible({kind:'ingredient',id:r.id,component:first},{kind:'ingredient',id:r.id,component:first}),null);for(const other of C.recipes.filter(x=>x!==r))assert.equal(E.compatible({kind:'ingredient',id:r.id,component:first},{kind:'ingredient',id:other.id,component:other.components[0].id}),null);assert.equal(E.compatible({kind:'dish',id:r.id},{kind:'ingredient',id:r.id,component:second}),null);}});
test('book buying spends funds and new collections must be opened',()=>{const s=fresh();s.board=Array(20).fill(null);const first=E.buyBook(s,'fiction');assert.equal(first.ok,true);assert.equal(first.price,10);assert.equal(s.funds,50);const random=E.buyBook(s);assert.equal(random.ok,true);assert.equal(random.price,6);assert.ok(s.unlockedSections.includes(random.section));assert.equal(s.funds,44);assert.equal(E.buyBook(s,'poetry').reason,'locked');assert.equal(E.buySection(s,'poetry'),false);s.served=4;s.funds=100;assert.equal(E.buySection(s,'poetry'),true);assert.equal(s.funds,10);assert.ok(s.unlockedSections.includes('poetry'));assert.equal(E.buySection(s,'poetry'),false);});
test('recipe research and pantry stock both spend funds and require board space',()=>{const s=fresh();assert.equal(E.stockRecipe(s,'fondue').reason,'locked');s.served=99;s.funds=1000;assert.equal(E.buyRecipe(s,'rarebit'),true);const afterResearch=s.funds;assert.equal(E.buyRecipe(s,'rarebit'),false);s.board=Array.from({length:20},()=>({kind:'book',tier:1,section:'fiction'}));for(let i=0;i<6;i++)E.returnItem(s,i);assert.equal(E.stockRecipe(s,'rarebit').reason,'space');E.returnItem(s,6);const result=E.stockRecipe(s,'rarebit');assert.equal(result.ok,true);assert.equal(result.indices.length,7);assert.deepEqual(result.indices.map(i=>s.board[i].component),E.recipe('rarebit').components.map(c=>c.id));assert.equal(s.funds,afterResearch-E.recipe('rarebit').stock);assert.equal(E.returnItem(s,100),false);});
test('fulfilment consumes exact required items and awards the specified funds',()=>{const s=fresh();assert.equal(E.serve(s,0).ok,false);E.move(s,0,1);E.move(s,5,6);const q=E.copy(s.requests[0]),n=E.neededIndices(s,q),funds=E.reward(s,q);assert.equal(funds,68);const result=E.serve(s,0);assert.equal(result.coins,funds);assert.equal(s.funds,128);assert.equal(s.board[n.book],null);assert.equal(s.board[n.dish],null);assert.equal(s.served,1);assert.equal(s.daily.served,1);assert.equal(s.visits[0],1);assert.equal(s.requests.length,3);assert.equal(s.orderIndex,4);});
test('larger books and wrong finished dishes cannot fulfil exact requests',()=>{const s=fresh();s.board=Array(20).fill(null);s.board[0]={kind:'book',tier:3};s.board[1]={kind:'dish',id:'manchego'};assert.equal(E.serve(s,0).ok,false);s.board[0].tier=2;s.board[1].id='wensleydale';assert.equal(E.serve(s,0).ok,false);});
test('reward calculation applies food percentage before room bonuses and flat amounts',()=>{const s=fresh();s.upgrades=['dresser','nook','club','terrace','glass','festival','lamps','atlas'];assert.equal(E.reward(s,s.requests[0]),Math.round((20+48*1.15)*1.5)+30);assert.equal(E.reward(s,s.requests[1]),40);});
test('purchases require funds, unique ownership and finale prerequisites',()=>{const s=fresh();assert.equal(E.buy(s,'trolley'),false);s.funds=100000;assert.equal(E.buy(s,'festival'),false);assert.equal(E.buy(s,'missing'),false);assert.equal(E.buy(s,'trolley'),true);assert.equal(s.funds,99820);assert.equal(E.buy(s,'trolley'),false);for(const u of C.upgrades.filter(x=>!['trolley','festival'].includes(x.id)))assert.equal(E.buy(s,u.id),true);assert.equal(E.buy(s,'festival'),true);assert.equal(s.upgrades.length,16);});
test('delivery upgrades create higher tiers with repeatable seeded randomness',()=>{const a=fresh(),b=fresh();a.upgrades=b.upgrades=['trolley','rare','loft'];const seen=new Set();for(let i=0;i<1000;i++){a.board=Array(20).fill(null);b.board=Array(20).fill(null);const x=E.spawnBook(a),y=E.spawnBook(b);assert.deepEqual(x,y);seen.add(x.tier);}assert.deepEqual([...seen].sort(),[1,2,3,4]);});
test('daily jobs pay once and a skipped date never removes funds or progress',()=>{const s=fresh();assert.equal(E.claimDaily(s),false);s.daily.served=3;assert.equal(E.claimDaily(s),true);assert.equal(E.claimDaily(s),false);assert.equal(s.funds,135);assert.equal(E.rotateDay(s,'2026-10-01'),true);assert.equal(s.funds,135);assert.deepEqual(s.daily,{date:'2026-10-01',served:0,claimed:false});assert.equal(E.rotateDay(s,'2026-10-01'),false);});
test('milestones pay exactly once and only when earned',()=>{const s=fresh();assert.equal(E.claim(s,'first'),false);s.served=1;assert.equal(E.claim(s,'first'),true);assert.equal(s.funds,100);assert.equal(E.claim(s,'first'),false);assert.equal(E.claim(s,'unknown'),false);});
test('save validation preserves the changed board, not the starter board',()=>{const s=fresh();E.move(s,0,1);E.move(s,5,6);E.spawnBook(s);const v=E.validate(s);assert.deepEqual(v,s);v.board[1].tier=6;assert.equal(s.board[1].tier,2);});
test('version-one saves migrate old books, two-tile food and visitor arrays',()=>{const s=fresh();delete s.catalogued;s.theme='sage';s.visits=s.visits.slice(0,8);s.board[0]={kind:'book',tier:1};s.board[5]={kind:'cheese',id:'manchego'};s.board[6]={kind:'prep',id:'manchego'};s.requests.forEach(q=>delete q.section);s.upgrades=['trolley','nook','lamps','dresser','plants','rare','club','atlas','terrace','glass','loft','festival'];s.seenEnding=true;const v=E.validate(s);assert.equal(v.theme,'teal');assert.equal(v.visits.length,12);assert.equal(v.seenEnding,false);assert.deepEqual(v.board[0],{kind:'book',tier:1,section:'fiction'});assert.deepEqual(v.board[5],{kind:'ingredient',id:'manchego',component:'manchego'});assert.deepEqual(v.board[6],{kind:'ingredient',id:'manchego',component:'membrillo'});assert.ok(v.requests.every(q=>E.section(q.section)));});
test('malformed saves are rejected across progress, board, collections and requests',()=>{for(const mutate of [s=>s.version=900,s=>s.board.pop(),s=>s.board[0]={kind:'book',tier:7},s=>s.board[1]={kind:'dish',id:'fiction'},s=>s.funds=-1,s=>s.seed=NaN,s=>s.upgrades=['trolley','trolley'],s=>s.discovered=['fake'],s=>s.requests[0].visitor=80,s=>s.requests[0].tier=0,s=>s.visits=[],s=>s.daily.served=-1,s=>s.daily.claimed='false',s=>s.dailyPuzzle={targets:['INVALID','UNKNOWN'],guesses:[],rewarded:false}]){const s=fresh();mutate(s);assert.throws(()=>E.validate(s));}});
test('duplicate-letter scoring reserves greens then consumes remaining letters',()=>{assert.deepEqual(E.feedback('BALLOON','COLONEL'),[0,0,2,1,1,1,1]);assert.deepEqual(E.feedback('TESSERA','TESSERA'),[2,2,2,2,2,2,2]);assert.deepEqual(E.feedback('AAAAAAA','FARRAGO'),[0,2,0,0,2,0,0]);assert.deepEqual(E.feedback('BANANAS','ANODYNE'),[0,1,1,0,1,0,0]);assert.throws(()=>E.feedback('SHORT','TOOLONG'));});
test('feedback multiplicity never exceeds target counts over 2401 generated cases',()=>{const words=[];for(let i=0;i<49;i++)words.push(Array.from({length:7},(_,j)=>'ABC'[Math.floor(i/3**j)%3]).join(''));for(const target of words)for(const guess of words){const f=E.feedback(guess,target);for(const ch of 'ABC')assert.ok(f.filter((x,i)=>x>0&&guess[i]===ch).length<=target.split(ch).length-1);for(let i=0;i<7;i++)assert.equal(f[i]===2,guess[i]===target[i]);}});
test('single puzzle wins once, rewards 80 funds and updates best',()=>{const s=fresh(),p=E.makePuzzle(19,W.answers);const miss=W.core.find(word=>word!==p.targets[0]);assert.equal(E.submitGuess(s,p,miss,allowed).done,false);assert.deepEqual(E.puzzleStatus(p).solved,[false]);assert.equal(s.funds,60);const r=E.submitGuess(s,p,p.targets[0],allowed);assert.equal(r.won,true);assert.equal(r.coins,80);assert.equal(s.puzzles,1);assert.equal(s.stats.best,2);assert.equal(E.submitGuess(s,p,'ACERBIC',allowed).ok,false);assert.equal(s.funds,140);s.dailyPuzzle=p;assert.doesNotThrow(()=>E.validate(s));});
test('six guesses produce a loss without removing funds',()=>{const s=fresh(),p=E.makePuzzle(19,W.answers);const misses=W.answers.filter(x=>!p.targets.includes(x)).slice(0,6);let result;for(const word of misses)result=E.submitGuess(s,p,word,allowed);assert.equal(result.done,true);assert.equal(result.won,false);assert.equal(result.coins,0);assert.equal(s.funds,60);assert.equal(s.puzzles,0);});
test('legacy dual-puzzle saves retain library progress and reset only the retired puzzle',()=>{const s=fresh();s.funds=777;s.dailyPuzzle={targets:['ACERBIC','ACOLYTE'],guesses:['ADIPOSE'],rewarded:false,date:'2026-09-13',input:''};const v=E.validate(s);assert.equal(v.funds,777);assert.equal(v.dailyPuzzle,null);});
test('invalid and repeated guesses cost nothing; input is normalised',()=>{const s=fresh(),p=E.makePuzzle(19,W.answers);assert.equal(E.submitGuess(s,p,'XX',allowed).ok,false);assert.equal(E.submitGuess(s,p,'ZZZZZZZ',allowed).ok,false);assert.equal(p.guesses.length,0);assert.equal(E.submitGuess(s,p,'acerbic',allowed).ok,true);assert.equal(E.submitGuess(s,p,'ACERBIC',allowed).ok,false);assert.equal(p.guesses.length,1);});
test('daily puzzle selection is deterministic, single-target and uses the familiar-weighted pools',()=>{const day=E.dateKey(new Date(2026,8,13,23,59));assert.equal(day,'2026-09-13');const get=d=>E.makePuzzle(E.hash('ShelfLife.daily.v2.'+d),W.answers,d);assert.deepEqual(get(day),get(day));assert.equal(get(day).targets.length,1);assert.notDeepEqual(get(day).targets,get('2026-09-14').targets);let core=0,challenge=0;for(let i=0;i<1000;i++){const word=E.makePuzzle(E.hash('pool.'+i),W.answers).targets[0];if(W.core.includes(word))core++;else if(W.challenge.includes(word))challenge++;else assert.fail('Inactive legacy target selected: '+word);}assert.ok(core>740&&core<850,`Unexpected core share: ${core}`);assert.equal(core+challenge,1000);assert.deepEqual(E.makePuzzle(0,['ACERBIC']).targets,['ACERBIC']);assert.throws(()=>E.makePuzzle(0,[]));});
test('impossible puzzle saves cannot acquire rewards or missing definitions',()=>{const s=fresh();s.dailyPuzzle=E.makePuzzle(4,W.answers);s.dailyPuzzle.rewarded=true;assert.throws(()=>E.validate(s));s.dailyPuzzle.rewarded=false;s.dailyPuzzle.targets[0]='ZZZZZZZ';assert.throws(()=>E.validate(s));});
test('a complete paid campaign can reach every upgrade, recipe and collection',()=>{
 const s=E.fresh(17,'2026-09-13');let actions=0;
 const move=(a,b)=>{assert.equal(E.move(s,a,b).ok,true);actions++;};
 const discardOne=keep=>{const i=s.board.findIndex((item,index)=>item&&!keep(item,index));assert.ok(i>=0,'Board deadlock');assert.equal(E.returnItem(s,i),true);actions++;};
 const ensureBook=q=>{
  while(!s.board.some(i=>i?.kind==='book'&&i.tier===q.tier&&i.section===q.section)){
   let merged=false;
   for(let tier=q.tier-1;tier>=1;tier--){const pair=s.board.map((x,i)=>x?.kind==='book'&&x.tier===tier&&x.section===q.section?i:-1).filter(i=>i>=0);if(pair.length>1){move(pair[0],pair[1]);merged=true;break;}}
   if(merged)continue;
   if(!s.board.includes(null))discardOne(item=>item.kind==='book'&&item.section===q.section&&item.tier<=q.tier||item.kind==='dish'&&item.id===q.recipe);
   const result=E.buyBook(s,q.section);assert.equal(result.ok,true,`Book purchase failed with ${result.reason}; funds ${s.funds}`);actions++;
   if(result.tier>q.tier){E.returnItem(s,result.index);actions++;}
  }
 };
 const ensureDish=q=>{
  if(!q.recipe||s.board.some(i=>i?.kind==='dish'&&i.id===q.recipe))return;
  const r=E.recipe(q.recipe);while(s.board.filter(x=>x===null).length<r.components.length)discardOne(item=>item.kind==='book'&&item.section===q.section&&item.tier===q.tier);
  const stocked=E.stockRecipe(s,q.recipe);assert.equal(stocked.ok,true,`Stock failed with ${stocked.reason}; funds ${s.funds}`);actions++;
  let target=stocked.indices[0];for(const next of stocked.indices.slice(1))move(next,target);assert.equal(s.board[target].kind,'dish');
 };
 const serveAffordable=()=>{
  for(let slot=0;slot<3;slot++){const q=s.requests[slot],r=q.recipe?E.recipe(q.recipe):null;if(!s.unlockedSections.includes(q.section)||r&&!s.unlockedRecipes.includes(r.id))continue;const rough=E.bookPrice(q.section)*2**(q.tier-1)+(r?r.stock:0);if(rough<=s.funds||E.neededIndices(s,q).ready){ensureBook(q);ensureDish(q);assert.equal(E.serve(s,slot).ok,true);actions++;return true;}}
  return false;
 };
 for(let turns=0;turns<900&&(s.upgrades.length<C.upgrades.length||s.discovered.length<C.recipes.length||s.unlockedSections.length<C.sections.length);turns++){
  for(const section of C.sections)if(!s.unlockedSections.includes(section.id)&&s.served>=section.unlock&&s.funds>=section.price+300){assert.equal(E.buySection(s,section.id),true);actions++;}
  for(const recipe of C.recipes)if(!s.unlockedRecipes.includes(recipe.id)&&s.served>=recipe.unlock&&s.funds>=recipe.research+350){assert.equal(E.buyRecipe(s,recipe.id),true);actions++;}
  if(s.served>=70&&s.discovered.length===C.recipes.length)for(const u of C.upgrades)if(s.funds>=u.price+400&&E.buy(s,u.id))actions++;
  if(!serveAffordable()){
   const locked=s.requests.find(q=>!s.unlockedSections.includes(q.section));
   if(locked){const section=E.section(locked.section);if(s.served>=section.unlock&&s.funds>=section.price){assert.equal(E.buySection(s,section.id),true);actions++;continue;}}
   assert.fail(`Campaign stalled at ${s.served} visitors with ${s.funds} funds`);
  }
  for(const recipe of C.recipes)if(s.unlockedRecipes.includes(recipe.id)&&!s.discovered.includes(recipe.id)&&s.funds>=recipe.stock+450){
   while(s.board.filter(x=>x===null).length<recipe.components.length)discardOne(()=>false);
   const stocked=E.stockRecipe(s,recipe.id);assert.equal(stocked.ok,true);let target=stocked.indices[0];for(const next of stocked.indices.slice(1))move(next,target);assert.equal(s.board[target].kind,'dish');E.returnItem(s,target);actions++;
  }
  for(const a of C.achievements)E.claim(s,a.id);E.claimDaily(s);
  assert.ok(actions<50000,'Campaign did not progress');
 }
 assert.equal(s.upgrades.length,16);assert.equal(s.discovered.length,24);assert.equal(s.unlockedRecipes.length,24);assert.equal(s.unlockedSections.length,6);assert.ok(s.served<900);assert.doesNotThrow(()=>E.validate(s));
});
