'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
function walk(p){return fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(p,e.name)):[path.join(p,e.name)]);}
function check(){const files=walk(path.join(root,'public'));for(const f of files){const s=fs.readFileSync(f,'utf8');if(f.endsWith('.js'))new vm.Script(s,{filename:f});if(!f.endsWith('WORDLIST-LICENCE.txt')&&!f.endsWith('words.js')){assert.ok(!/\b(?:coffee|tea)[ -]?(?:mug|cup)s?\b|\bmugs?\b|great books,? great people|small library,? big happiness|brighter days|books make everything better|kind people,? great books|TODO|coming soon|placeholder/i.test(s),'Banned or unfinished content: '+f);}if(/\.(js|css|html|webmanifest)$/.test(f)){const stripped=s.replace(/http:\/\/www\.w3\.org\/2000\/svg/g,'');if(!f.endsWith('content.js'))assert.ok(!/https?:\/\//.test(stripped),'Remote runtime URL: '+f);assert.ok(!/(?:src|href)=["']\/\/|@import|fetch\(["']https|url\(["']?https/i.test(s),'Remote runtime dependency: '+f);}}
const C=require('../public/src/content.js'),W=require('../public/data/words.js');for(const key of ['recipes','sections','visitors','upgrades','achievements']){const ids=C[key].map(x=>x.id);assert.equal(new Set(ids).size,ids.length);assert.ok(ids.every(x=>/^[a-z][a-z0-9-]*$/.test(x)));}assert.equal(C.recipes.length,10);assert.equal(C.sections.length,6);assert.equal(C.visitors.length,12);assert.equal(C.upgrades.length,16);assert.equal(C.achievements.length,8);
const ids=JSON.parse(fs.readFileSync(path.join(root,'tests/content-ids.json'),'utf8'));for(const k of Object.keys(ids))assert.deepEqual(C[k].map(x=>x.id),ids[k],'Save IDs changed: '+k);
const complexities=new Set();for(const r of C.recipes){for(const field of ['id','name','cheese','partner','region','ingredients','fact','detail'])assert.ok(r[field]?.length,'Missing recipe '+field);assert.ok(r.sources.length);assert.ok(r.components.length>=2&&r.components.length<=7);assert.equal(new Set(r.components.map(c=>c.id)).size,r.components.length);for(const c of r.components){assert.ok(c.id&&c.name&&c.kind);}complexities.add(r.components.length);for(const [title,url] of r.sources){assert.ok(title.length>5);assert.equal(new URL(url).protocol,'https:');}}for(const n of [2,3,4,5,6,7])assert.ok(complexities.has(n),'Missing '+n+'-component preparation');
const allowed=new Set(W.allowed.split(' '));assert.ok(allowed.size>20000);assert.ok(W.answers.length>=40);for(const w of W.answers){assert.match(w,/^[A-Z]{7}$/);assert.ok(allowed.has(w));assert.ok(W.definitions[w]?.definition.length>10);assert.ok(W.definitions[w]?.note.length>10);assert.ok(!['READING','LIBRARY','BOOKING','FRIENDS'].includes(w));}assert.equal(new Set(W.answers).size,W.answers.length);
for(const file of ['index.html','styles.css','src/content.js','src/storage.js','src/art.js','data/words.js','data/WORDLIST-LICENCE.txt','manifest.webmanifest','sw.js','assets/icon.svg'])assert.ok(fs.existsSync(path.join(root,'public',file)));
const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');for(const [,asset] of html.matchAll(/(?:src|href)="([^"#]+)"/g))assert.ok(fs.existsSync(path.join(root,'public',asset)),'Missing shell asset '+asset);
JSON.parse(fs.readFileSync(path.join(root,'public/manifest.webmanifest'),'utf8'));console.log(`PASS: syntax, stable IDs, 10 researched recipes with 2–7 components, 6 book sections, ${allowed.size} guesses / ${W.answers.length} targets, banned content and local runtime assets.`);}
if(require.main===module)check();module.exports=check;
